version: '3.4'
volumes:
  postgres_volume:
    name: ${POSTGRES_VOLUME_NAME}
services:
  postgis:
    image: bde2020/postgis
    hostname: postgis
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - postgres_volume:/var/lib/postgresql/9.4/main:rw
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - multinav-net
  strabon:
    build:
      context: ./strabon-context
    hostname: strabon
    environment:
      - STRABON_CONNECTION_hostname=${POSTGRES_ORDBMS}
      - STRABON_CONNECTION_port=${POSTGRES_PORT}
      - STRABON_CREDENTIALS_username=${STRABON_CREDENTIALS_username}
      - STRABON_CREDENTIALS_password=${STRABON_CREDENTIALS_password}
    ports:
      - "${STRABON_PORT}:8080"
    networks:
      - multinav-net
  udviz:
    build:
      args:
        - checkoutName=hot-fix #branch or sha of commit
      context: ./udviz-context
    ports:
      - "${UD_VIZ_PORT}:80"
    networks:
      - multinav-net

networks:
  multinav-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
      com.docker.network.bridge.name: br-multidata