version: '3.4'

services:

  blazegraph:
    image: vcity/blazegraph-cors
    ports:
      - "${BLAZEGRAPH_PORT}:8080"
    networks:
      - multinav-net

  udviz:
    build:
      args:
        - checkoutName=hot-fix #branch or sha of commit
      context: ./udviz-context
    ports:
      - "${UD_VIZ_PORT}:80"
    networks:
      - multinav-net

networks:

  multinav-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
      com.docker.network.bridge.name: br-multidata